name: sytex_coding_challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-444.4.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  sytex_repository:
    path: packages/sytex_repository
  sytex_service:
    path: packages/sytex_service

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
